name: Movie Chunk Generator

on:
  workflow_dispatch:
    inputs:
      Input_Movie_Link:
        description: "Direct URL for Movie"
        required: true
        default: ""

env:
  LocationOnIndex4MovieChunks: "td:/MovieChunks"
  Input_Movie_Link: ${{ github.event.inputs.Input_Movie_Link }}
  RCLONE_CONFIG_URL: ${{ secrets.RCLONE_CONFIG_URL }}

jobs:

  splitter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set Git Configs & Secrets
        uses: rokibhasansagar/custom_workflows/git_config@main
        with:
          credential: "yes"
        env:
          PAT: ${{ secrets.GH_TOKEN }}

      - name: "Movie Chunk Generation Job - ${{env.Input_Movie_Link}}"
        run: |
          chmod a+x ./*.sh
          bash ./chunkerScript.sh
